### ISSUE TITLE
Is it possible to get php7 support?

### ISSUE THREAD

**Issue by mercymantis** [vultr/vultr-php#10]
I have many reasons for this request.  

1) Stable distributions ( production environments ) haven't fully adopted php8.  
2) The latest Ubuntu release defaults to php7 ( in my case php8 was a headache to get working )
3) Not all modules have or are php8 friendly, I had to use custom/questionable repos and still failed due to a buggy module. 

The only way I can run this library is through a docker image. Perhaps other people are experiencing similar issues.

**Comment by Porthorian** [comment]
@mercymantis this is something we will take into consideration. As of this moment though we have no plans to support php 7.4. This is largely due to the fact that php7.4 will be EOL in November of 2022 https://www.php.net/supported-versions.php.

There are also other reasons why we decided to limit the support of this library to php 8.0 and on. This is due to the fact that with 8.0 we were given the opportunity to use Union Types. Which makes using the library a bit more statically typed. I started a 7.4 branch to see how much work would need to be done to get the lib working with 7.4. But I give no promises, as I do not wanna have to create work arounds to keep support for php 8.0 and on.

Granted the migration path from 7.4 to 8.0 isn't that bad. I'd highly suggest to explore adopting 8.0.

Ill keep this open if you have any questions, and am willing to assist you with any questions you may have.

**Comment by mercymantis** [comment]
Sorry, I never responded, just got busy with setting up software on Vultr.
I ended up using the vultr-cli to accomplish what I needed as php8 on
production isn't doable at the moment.
